# TODO: Working
# TODO AGWEC2Instance: Value (us-west-1b) for parameter availabilityZone is invalid. Network interface 'eni-0e744e59ffa6404c0' is in the availability zone us-west-1c (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 93056364-6907-4ffd-9fb1-a51b958d6098; Proxy: null)

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access into the resources
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  AgwSrsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "AgwSrsVPC"

  S1SrsPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-west-1c"
      MapPublicIpOnLaunch: true
      VpcId: !Ref "AgwSrsVPC"
      Tags:
        - Key: Name
          Value: "S1SrsSubnet"
          # Value: "S1SrsSubnet - us-west-1b"

  AgwPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-west-1c"
      MapPublicIpOnLaunch: true
      VpcId: !Ref "AgwSrsVPC"
      Tags:
        - Key: Name
          Value: "AgwSubnet"
          # Value: "AgwSubnet - us-west-1c"

  AgwSrsIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: "AgwSrsIGW"

  AgwSrsNetworkACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref "AgwSrsVPC"
      Tags:
        - Key: Name
          Value: "AgwNetworkACL"

  AgwSrsRoutePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref "AgwSrsVPC"
      Tags:
        - Key: Name
          Value: "AgwSrsRoutePublic"

  AGWEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-03f6d497fceb40069
      KeyName: !Ref KeyName
      Monitoring: false
      UserData: "echo hello world"
      # SubnetId: !Ref AgwPublicSubnet
      NetworkInterfaces:
        # - AssociatePublicIpAddress: true
        #   DeleteOnTermination: true
        #   Description: AGW SGi network interface.
        #   DeviceIndex: "0"
        #   SubnetId: !Ref "AgwPublicSubnet"
        #   GroupSet: [!Ref "SGAgw"]
        - NetworkInterfaceId: !Ref AGWSGiNetworkInterface
          DeviceIndex: 0
        - NetworkInterfaceId: !Ref AGWS1NetworkInterface
          DeviceIndex: 1
      Tags:
        - Key: Name
          Value: "AGWEC2Instance"

  AGWSGiNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: AGW SGi network interface, internet access.
      GroupSet: [!Ref "SGAgw"]
      SubnetId: !Ref AgwPublicSubnet
      Tags:
        - Key: Name
          Value: "AGWS1NetworkInterface"

  EIPSGi:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: "SGi Elastic IP"

  EIPSGiAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EIPSGi.AllocationId
      NetworkInterfaceId: !Ref AGWSGiNetworkInterface

  AGWS1NetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: AGW S1 network interface.
      GroupSet: [!Ref "SGAgw"]
      SubnetId: !Ref S1SrsPublicSubnet
      Tags:
        - Key: Name
          Value: "AGWS1NetworkInterface"

  SrsEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-03f6d497fceb40069
      KeyName: !Ref KeyName
      Monitoring: false
      UserData: "echo hello world"
      # SubnetId: !Ref S1SrsPublicSubnet
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          Description: Primary network interface for srs
          DeviceIndex: "0"
          SubnetId: !Ref "S1SrsPublicSubnet"
          GroupSet: [!Ref "SGsrs"]
      Tags:
        - Key: Name
          Value: "SrsEC2Instance"

  SGsrs:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Srs host security group
      VpcId: !Ref "AgwSrsVPC"
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SrsHostSecurityGroup

  SGAgw:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Srs host security group
      VpcId: !Ref "AgwSrsVPC"
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SrsHostSecurityGroup

  NACLEntry1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
      NetworkAclId: !Ref "AgwSrsNetworkACL"

  NACLEntry2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
      NetworkAclId: !Ref "AgwSrsNetworkACL"

  subnetaclS1Srs:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref "AgwSrsNetworkACL"
      SubnetId: !Ref "S1SrsPublicSubnet"

  subnetaclSrs:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref "AgwSrsNetworkACL"
      SubnetId: !Ref "AgwPublicSubnet"

  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref "AgwSrsVPC"
      InternetGatewayId: !Ref "AgwSrsIGW"

  subnetRoutePublicS1Srs:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref "AgwSrsRoutePublic"
      SubnetId: !Ref "S1SrsPublicSubnet"

  subnetRoutePublicAgw:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref "AgwSrsRoutePublic"
      SubnetId: !Ref "AgwPublicSubnet"

  publicroute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref "AgwSrsRoutePublic"
      GatewayId: !Ref "AgwSrsIGW"
