name: Link check

on:
  - push
  - pull_request

jobs:
  linkcheck:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install the doc framework
        run: |
          cd docs && make install

      - name: Run linkchecker
        run: |
          cd docs && make linkcheck
