name: orc8r-certifier

on:
  push:
    paths:
      - "orchestrator-bundle/orc8r-certifier-operator/**"

jobs:
  orc8r-certifier-lint-report:
    name: Lint report (orc8r-certifier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd orchestrator-bundle/orc8r-certifier-operator && tox -e lint

  orc8r-certifier-static-analysis:
    name: Static analysis (orc8r-certifier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd orchestrator-bundle/orc8r-certifier-operator && tox -e static

  orc8r-certifier-unit-tests-with-coverage:
    name: Unit tests (orc8r-certifier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd orchestrator-bundle/orc8r-certifier-operator && tox -e unit

  orc8r-certifier-integration-test:
    name: Integration tests (orc8r-certifier)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
      - name: Run integration tests
        run: |
          sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3-venv=3.8.2-0ubuntu2 python3.8-venv=3.8.10-0ubuntu1~20.04.4
          sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install cargo=0.58.0-0ubuntu1~20.04.1 libffi-dev=3.3-4 libssh2-1=1.8.0-2.1build1 libssl-dev=1.1.1f-1ubuntu2.13 libstd-rust-1.57=1.57.0+dfsg1+llvm-0ubuntu1~20.04.1 libstd-rust-dev=1.57.0+dfsg1+llvm-0ubuntu1~20.04.1 rustc=1.57.0+dfsg1+llvm-0ubuntu1~20.04.1
          cd orchestrator-bundle/orc8r-certifier-operator && tox -e integration
