name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
      - 1.6

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64      
          cache: 'pip'                      
      - name: Install Python dependencies
        run: python3 -m pip install -r 'requirements-doc.txt'
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mike deploy --push ${{ github.ref_name }}
