name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
      - 1.6

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install mkdocs
        run: python3 -m pip install mkdocs
      - name: Install mkdocs-material
        run: python3 -m pip install mkdocs-material
      - name: Install mike
        run: python3 -m pip install mike
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mike deploy --push ${{ github.ref_name }}
