name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
      - 1.8

jobs:
  build:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python dependencies
        run: python3 -m pip install -r 'requirements-doc.txt'
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions-bot@users.noreply.github.com"
          git config --local user.name "github-actions-bot"
      - name: mike deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mike deploy --push ${{ github.ref_name }}
