name: Publish docs via GitHub Pages
on:
  push:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Install Python dependencies
        run: python3 -m pip install -r 'requirements-doc.txt'
      - name: Deploy docs
        if: github.ref_name == 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mike deploy --push ${{ github.ref_name }}
